### ISSUE TITLE
Missing VSIX file

### ISSUE THREAD

**Issue by tirnovar** [microsoft/vscode-powerquery-sdk#107]
Hello everyone,
I was about to test this SDK, but the VSIX file is missing or hidden. Is it on purpose?

Thank you for your answer.
Štěpán

**Comment by albertli-msft** [comment]
Hi @tirnovar:

Could you have a try of the https://github.com/microsoft/vscode-powerquery-sdk/releases
And let us know whether it still got hidden from you or not

Thanks

**Comment by tirnovar** [comment]
Yes! It works. But it seems like an error on the cache level because I can see releases on mobile and not on PC. Thank you. I am going to test it.
