### ISSUE TITLE
Make it clear that the SDK only supports Windows platform

### ISSUE THREAD

**Issue by tirnovar** [microsoft/vscode-powerquery-sdk#109]
Hello, I have installed VSIX on my MacBook. The workspace was settled correctly, but then it dropped into an endless loop with Display extension info, and if I canceled it and tried to run anything else like "Set credentials," it went into a loop also.
 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/78301524/191976755-f5b56694-fb10-42a9-89b4-5c33239953ce.png">

I have tried the same on a Windows machine, and it works.

**Comment by mattmasson** [comment]
The SDK (or more specifically, the backend sdktools package we use for M evaluation) currently only supports windows.

While we have PQ/M running on mac (for Excel), the engine doesn't have full parity with the Windows version. The mac engine runs under .net core, which doesn't have the full set of data providers available (or an ODBC stack), and there some behavior differences vs. net472 that we need to smooth out before we could consider supporting the SDK tools on non-windows OS. We want evaluations to run the same in the SDK as they do in desktop/power bi/gateway/dataflows/etc to avoid environment specific bugs/issues.

I'll rename this issue to reflect that the extension should warn that it is windows only.

**Comment by tirnovar** [comment]
I understand. That's why I prefer to ask. However, because I usually find that extensions in Visual Studio Code support any environment (at least the ones I use), I had to try it because I didn't even notice that it was mentioned in the description. So far, everything I've tried on Windows has worked. I tested my old connector there and was able to build, edit, run and debug it and get data! You have done fantastic work. No need to do it in Visual Studio anymore, but I can finally use Code.

**Comment by bgribaudo** [comment]
Would setting an OS dependency in the extension's package.json prevent installing on non-supported OSes?

**Comment by mattmasson** [comment]
> Would setting an OS dependency in the extension's package.json prevent installing on non-supported OSes?

That was my first thought - we could set `"os": [ "win32" ]` in the package.json. I couldn't find anything in the VSCode docs indicating that they honor/check this field when you publish to the marketplace, and I doubt it'll block things if you install the vsix manually.

Either way, we shouldn't end up in an infinite loop. If we can't block the install, then I'm hoping we can throw an error before we try to download the SdkTools nuget.
