### ISSUE TITLE
Output Pane - Ignores column if value is null in first row

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#110]
If a table's first row contains null for a particular column, the _Output_ pane ignores the **entire** column (so values from it are not displayed for _any_ row).

The below repo connector returns a table containing two columns; however, as the below screenshot shows, the _Output_ pane skips displaying `Column1`.

![Demo](https://user-images.githubusercontent.com/857202/191980451-36819fa9-5ef3-43fe-b01c-642cc4a0cdf8.png)

## Repo
````
[Version = "1.0.0"]
section BenTest;

[DataSource.Kind="BenTest"]
shared BenTest.Contents = () =>
    #table(
        null, 
        {
            {null, "col 2 - row1"},
            {"col 1 - row 2", "col 2 - row 2"}
        }
    );

BenTest = [
    Authentication = [
        Anonymous = []
    ]
];
````

**Comment by mattmasson** [comment]
This should be fixed in the latest SDK tools release.

![image](https://user-images.githubusercontent.com/5509937/192318639-8f75bfe4-bf29-449c-8c9f-42501991e835.png)

**Comment by bgribaudo** [comment]
Thanks!
