### ISSUE TITLE
Output Pane - Duration value can cause blank output pane

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#111]
I'm enjoying playing with the new connector. I really appreciate the work the team has put into this. Thank you!

If it helps, here's another issue I ran into:

Apparently, a column that contains a duration can break the _Output_ pane so that it displays nothing. :-(
![image](https://user-images.githubusercontent.com/857202/191982218-b2894488-bc29-44f5-a9b1-0fb04cc54353.png)

In the generated JSON, duration values are rendered as nested objects, which I suspect is related to this problem.
````
"Output": [
    {
        "Employee": "Joe",
        "Hours Worked": {
            "Ticks": 4357230000000,
            "Days": 5,
            "Hours": 1,
            "Milliseconds": 0,
            "Minutes": 2,
            "Seconds": 3,
            "TotalDays": 5.043090277777778,
            "TotalHours": 121.03416666666666,
            "TotalMilliseconds": 435723000,
            "TotalMinutes": 7262.05,
            "TotalSeconds": 435723
        }
    },
    ...
]
````

Related: Instead of rendering out a duration's individual properties, would it make sense to use something like [ISO 8601's duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations)?

## Repo
````
[Version = "1.0.0"]
section BenTest;

[DataSource.Kind="BenTest"]
shared BenTest.Contents = () =>
    #table(
        {"Employee", "Hours Worked"}, 
        {
            {"Joe", #duration(5, 1, 2, 3)},
            {"Bob", #duration(5, 1, 2, 3)}
        }
    );

BenTest = [
    Authentication = [
        Anonymous = []
    ]
];
````

**Comment by mattmasson** [comment]
Fixed in the 2.110.2 release of the SDK Tools nuget (which should be automatically downloaded by the preview VSIX).
