### ISSUE TITLE
VSIX Missing for Release 0.1.5

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#129]
This release's assets do not include the VSIX. :-)

https://github.com/microsoft/vscode-powerquery-sdk/releases/tag/v0.1.5

![image](https://user-images.githubusercontent.com/857202/192633183-69b0dad4-1e99-4b17-be5e-37e406152b34.png)

**Comment by mattmasson** [comment]
Fixed!

**Comment by bgribaudo** [comment]
Thanks!
