### ISSUE TITLE
Environment.Configuration() - no ouput

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#131]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.1.5

### Platform

Windows

### Architecture

x64

### OS Version

Windows 10 Pro

### Bug Description

Using the SDK, when `Environment.Configuration()` is run from inside a data connector, nothing is output. In contrast, when this method is run in Power BI from inside a data connector, various configuration key+value pairs are listed out (see below screenshot).

![image](https://user-images.githubusercontent.com/857202/192791565-ebf44764-c52d-4cba-ad42-bcfc695098e1.png)

Should the SDK's output contain something similar?

### Steps to Reproduce

* Demo connector:
````
[Version = "1.0.0"]
section BenTest;

[DataSource.Kind="BenTest"]
shared BenTest.Configuration = () =>
    Environment.Configuration();

SomeHelper = 123;

BenTest = [
    Authentication = [
        Anonymous = []
    ]
];
````
* Demo test code:
````
let
    Result = BenTest.Configuration()
in
    Result
````

### Actual Experience

See problem description

### Expected Experience

See problem description

**Comment by mattmasson** [comment]
This is by design, since the SDK doesn't set these "environment settings" by default. PQTest allows you to set arbitrary settings on the command line, but there are no plans to expose this through the UX at this time. 

Note that connectors shouldn't be taking any sort of dependency on these settings at this point, as they aren't publicly documented.

**Comment by bgribaudo** [comment]
Thanks!

I was able to pass in an environment config setting by adding `-ec RunFastTestRing=true` to PQTest's arguments.

The ability to pass in environment config could have some usefulness in CI/CD situations, like the ability for the external test runner to signal in whether it wants just the fast test ring run, or wither the full test suite should be run. Of course, to pull this off smoothly would require that `Environment.Configuration` stay exposed to the .query.pq test files, instead of being limited to only being accessible from inside data connector extension context (#114).
