### ISSUE TITLE
"Set credential" command should allow user provided values for data source kind and query file path

### ISSUE THREAD

**Issue by mattmasson** [microsoft/vscode-powerquery-sdk#154]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.1.7

### Platform

Windows

### Architecture

x64

### Bug Description

The commands to set credentials should allow arbitrary user input. 

Data Source Kind
- Try to detect the current connector's data source kind(s) and display them in the drop down
- Allow user to enter their own value

Authentication Kind
- If we have a known data source kind, display the supported kinds
- If we aren't sure, show all possible data source kinds in drop down

Query File
- Drop down should show *.query.pq and *.test.pq files
- Allow user to enter the path themselves

### Steps to Reproduce

Run **Set credential** command

### Actual Experience

N/A

**Comment by bgribaudo** [comment]
Related (or maybe implied by the above):

Any chance `pqTest set-credential` could allow the data source to be manually specified and, when specified, not require that an extension/query file/expression be provided?

This would allow something like the following to work:
`pqTest set-credential -dataSource BenTest -ak Anonymous`

Which is much shorter than the current:
````
pqTest set-credential
  --extension "c:\Users\ben\Desktop\TestConnector\BenTest\bin\AnyCPU\Debug\BenTest.mez"
  --queryFile "c:\Users\ben\Desktop\TestConnector\BenTest\BenTest.query.pq"
  -ak Anonymous
````

**Comment by mattmasson** [comment]
> Any chance pqTest set-credential could allow the data source to be manually specified and, when specified, not require that an extension/query file/expression be provided?

You can manually specify the Kind using `-dsk | --dataSourceKind` and the Path using `-dsp | --dataSourcePath`. 

Using a query file instead of manually the kind/path is easier and less error prone - it's easy to get the path wrong. 

The extension file is required to create the credential in our system.
