### ISSUE TITLE
pqtest set-credentials ignores -ak when JSON template used

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#157]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.1.7

### Platform

Windows

### Architecture

x64

### Bug Description

When setting credentials using a JSON template, if `pqtest set-credential` is passed argument `-ak`, it is ignored.

### Steps to Reproduce

1. Save the following credentials template to a text file:
````
{
  "AuthenticationKind": "Key",
  "AuthenticationProperties": {
    "Key": "some key"
  },
  "PrivacySetting": "None",
  "Permissions": []
}
````
2. Execute the following command using PowerShell:
````
get-content ~\Desktop\Template.txt | c:\Users\ben\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.1.7-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.110.3\tools\PQTest.exe set-credential `
>> --extension "c:\Users\...SomeConnector.mez" `
>> --queryFile "c:\Users\...SomeConnector.query.pq" `
>> --prettyPrint -ak Anonymous
````

*Notice* that the command line specifies an authentication kind of "Anonymous" while the template specifies "Key".

### Actual Experience

Command runs successfully.

### Expected Experience

Expect an error because the authentication kind in the template does not match the kind specified on the command line.

Idea: Error _any_ time `-ak` is specified when a template is used ("-ak/--authenticationKind cannot be specified as an argument when credentials are set using JSON").

**Comment by mattmasson** [comment]
This will be resolved in the next SDK Tools update (ETA 11/4).
