### ISSUE TITLE
AAD access token not refreshed when using AAD authentication kind

### ISSUE THREAD

**Issue by dbeavon** [microsoft/vscode-powerquery-sdk#164]
Can we get a fix for the "AAD authentication kind"? The token doesn't refresh correctly after it expires in about an hour. 

Whenever our custom connector is running on the desktop then everything works. But when it is running on an enterprise gateway, our PQ dies after an hour.  I think you would be able to encourage the development of more connectors by first fixing a basic issue like this in your AAD-based tokens.  This issue is VERY painful - because it can happen when you least expect, for reasons like slow data sources, or increasing amounts of source data.

This seems like an easy thing to fix given that the PBI desktop's mashup engine is working properly. There isn't any conceptual reason why the engine in the enterprise gateway should NOT be able to refresh an AAD access token just as the desktop does. 

Lots of people are stumbling on this. Your premium customers expect PQ to run for up to [five hours](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios#scheduled-refresh-timeout) before failures. Absolutely no customers expect this type of a basic token problem when the Power BI mashup engine is authenticating against the AAD .

Here is more information about AAD authentication and related refresh failures:

[Refresh failures.](https://disq.us/url?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-bi%2Fconnect-data%2Frefresh-troubleshooting-refresh-scenarios%23refresh-fails-when-updating-data-from-sources-that-use-azure-ad-oauth%3AiAYTBta9LYcOGo7D7zxtIkL-YOI&cuid=3987094)

**Comment by ptyx507x** [comment]
Hey!

Thank you for posting this. I've shared this feedback with the appropriate team who handles the Data Gateway. You can also post this feedback on the [official issues for Power BI](https://community.powerbi.com/t5/Issues/idb-p/Issues).

This GitHub repository is primarily for issues, discussions and suggestions related to the Power Query SDK. The issue described above is specific to the Gateway and independent of the SDK.

We hope that you give this new SDK a try and share your feedback with us around it. We are tackling as many suggestions and bugs as we can for the Power Query SDK in Visual Studio Code, and our main source of feedback is this GitHub repository. 

Thanks again!
