### ISSUE TITLE
"ConnectorInfo command --help" doesn't work

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#167]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.1.7

### Platform

Windows

### Architecture

x64

### Bug Description

When ConnectorInfo is run without any arguments, it outputs the following text:
````
Usage: ConnectorInfo [arguments] [options] [command]

Arguments:
  Connector file   Full path to connector (.mez/.pqx)
  Expression file  Full path to a file containing an M expression (.m/.pq)

Options:
  -?  | -h | --help  Show help information

Commands:
  dsr      Extracts DSR from expression.
  kind     Returns data source kind information.
  module   Returns the module name or an error if missing.
  version  Returns module version information or an error if missing.

Use "ConnectorInfo [command] --help" for more information about a command.
````

However, the help option reported by the last line does not work.

### Steps to Reproduce

````
PS> .\ConnectorInfo.exe dsr --help

Unhandled Exception: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--help'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ConnectorInfo.Program.Main(String[] args)
````

### Actual Experience

A textual rendering of an exception is output.

### Expected Experience

Descriptive help text should be output.

### Additional Context

Similar exception output occurs if other `-args` values (like `-x`) are used. Instead, shouldn't a user-friendly error about `-x` being an invalid argument be displayed?

**Comment by mattmasson** [comment]
This will be resolved in the next SDK Tools update (ETA 11/4).

**Comment by bgribaudo** [comment]
Thanks, Matt!
