### ISSUE TITLE
dataSourcePath not available for StartLogin when Setting Credentials

### ISSUE THREAD

**Issue by waldyd** [microsoft/vscode-powerquery-sdk#176]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.1.7

### Platform

Windows

### Architecture

x64

### OS Version

Windows 10

### VSCode version

1.72.2

### PQSdkTool Path

c:\Users\*****\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.1.7-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.110.3\

### Bug Description

While setting the credentials for my custom connector, the dataSourcePath value seems not reaching the StartLogin method:

![image](https://user-images.githubusercontent.com/1531796/197105526-6b7af660-3d89-4933-8441-82a22034c162.png)

You may notice that the AuthorizeUrl is taking the "else" value.

### Steps to Reproduce

1. Modify the dataSourcePath value in the query.pq file
2. Issue the Set Credentials command
3. dataSourcePath variable not reaching the  StartLogin method

### Actual Experience

The dataSourcePath value seems not reaching the StartLogin method:

![image](https://user-images.githubusercontent.com/1531796/197105526-6b7af660-3d89-4933-8441-82a22034c162.png)

After issuing the Set Credentials command, always the same Authorize site:
![image](https://user-images.githubusercontent.com/1531796/197105821-00dd0784-af18-46b9-95b7-24644c7c497e.png)

You may notice that the AuthorizeUrl is always taking the "else" value.

### Expected Experience

dataSourcePath json value being available for the StartLogin method.

**Comment by mattmasson** [comment]
I'm not sure what could be happening here. I'm unable to reproduce locally. 

Out of curiosity, does the connector behave as expected when you test it out in Power BI Desktop?
