### ISSUE TITLE
Auxiliary .pqm files not being included in .mez

### ISSUE THREAD

**Issue by denodo-research-labs** [microsoft/vscode-powerquery-sdk#192]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.0

### Platform

Windows

### Architecture

x64

### OS Version

Windows 10 Pro

### VSCode version

1.73.1

### Bug Description

We are trying to migrate a PowerQuery connector project from Visual Studio to VS Code using the new SDK and we find that, when we build the project using the _"Build connector project using MakePQX"_ task, the two auxiliary `.pqm` files present in our connector project are never included in the built `.mez`

```xml
<Project ...>
  ...
  <ItemGroup>
    ...
    <Compile Include="diagnostics\Diagnostics.pqm">
      <SubType>Content</SubType>
    </Compile>
    <Compile Include="validation\Validation.pqm">
      <SubType>Content</SubType>
    </Compile>
  </ItemGroup>

</Project>
```

Do we need to perform any additional configurations to make this build include this files using the new SDK?

Also, Visual Studio renames our main `.pq` file to `.m` in the `.mez` file, wheres we are finding that the new SDK in VS Code does not and it keeps it as `.pq`. Is this expected behaviour?

### Steps to Reproduce

1. Create a connector project with a `.pq` and one or several auxiliary `.pqm`.

2. Build using _"Build connector project using MakePQX"_.

### Actual Experience

The resulting `.mez` does not include the auxiliary `.pqm` and therefore does not work.

**Comment by bgribaudo** [comment]
If you move your `.pqm` files into the project's root folder, do they get included in the `.mez`? IIRC, the SDK build process only pulls files from the root directory.

**Comment by denodo-research-labs** [comment]
Confirmed. If we move those `.pqm` files to the root of the project and change the `<ItemGroup>` in the `.mproj` file accordingly, these files get included in the `.mez` build.

**Comment by bgribaudo** [comment]
The new SDK offers two build experiences: SDK-style builds and MSBuild-powered builds. 

The SDK-style build grabs most files _from the root directory_ and zips them up into the `.mez`. This build style does not rely on a `.mproj` or `.proj` file being present. If SDK-style building meets your needs, you might consider deleting your `.mproj` file as this style build doesn't use it.

If you'd like to use the new-style MSBuild-powered build, then a good starting place would be to create a brand-new connector project, grab its `.proj` file, copy it into your existing connector project, then edit it to align with your existing connector's needs, then delete your old `.mproj` file. You can then use the msbuild command to build using the new `.proj` file (or, I believe, even reconfigure things in VSCode to default to using MSBuild for connector projects).

**Comment by denodo-research-labs** [comment]
>  You can then use the msbuild command to build using the new .proj file (or, I believe, even reconfigure things in VSCode to default to using MSBuild for connector projects).

We are evaluating migration of the development of this component from Visual Studio to VS Code. Would MSBuild-powered builds mimic what Visual Studio currently does for our connector project? If not, is there a way with the _new SDK_ to obtain the same functionality we currently have in Visual Studio?

Also, where would we get this `msbuild` command in order to make the vscode-based task for MSBuild work? Would we need to use a `msbuild` command from a Visual Studio installation?

**Comment by bgribaudo** [comment]
> Also, where would we get this msbuild command in order to make the vscode-based task for MSBuild work? Would we need to use a msbuild command from a Visual Studio installation?

To get `msbuild`, you'll need either Visual Studio, Build Tools for Visual Studio (look under _All Downlaods_, _Tools for Visual Studio_ at https://visualstudio.microsoft.com/downloads/), or the [.Net SDK](https://learn.microsoft.com/en-us/dotnet/core/sdk#acquiring-the-net-sdk).

**Comment by bgribaudo** [comment]
> Would MSBuild-powered builds mimic what Visual Studio currently does for our connector project? 

Effectively, yes. I'd suggest giving it a try, then posting issues in this repo if you encounter any challenges.
