### ISSUE TITLE
Trailing comment causes parsing to die

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#194]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.0

### Platform

Windows

### Architecture

x64

### Bug Description

Attempting to evaluate an expression that ends with a comment dies with a syntax error.

### Steps to Reproduce

In a connector project, set the `.query.pq` file's contents to the following, then attempt to evaluate the file:
````
1  //hi
````

### Actual Experience

PQTest dies with a syntax error complaining that a semicolon was expected. 

````
[10:18:12 AM]	[Info]	[Task found] c:\Users\ben\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.0-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.111.5\tools\PQTest.exe run-test
				--extension "c:\Users\ben\Desktop\TestConnector\BenTest\bin\AnyCPU\Debug\BenTest.mez"
				--queryFile "c:\Users\ben\Desktop\TestConnector\BenTest\BenTest.query.pq"
				--prettyPrint
[10:18:12 AM]	[Error]	[Task exited abnormally] pqtest run-test pid(19256) exit(4294967291) stderr: Error: exception while running expression.: Token Semicolon expected. Start position: (2, 33). End position (2, 33).
````

### Expected Experience

The above expression should evaluate successfully, returning 1.

**Comment by mattmasson** [comment]
This should be resolved in the `2.112.x` release of the SdkTools package.
