### ISSUE TITLE
Log File Missing Correlation IDs

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#217]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.1

### Platform

Windows

### Architecture

x64

### Bug Description

When `PQTest.exe run-test` is asked to output a log file, each line of the outputted logfile contains a blank correlation ID.

### Steps to Reproduce

1. Create a basic extension project.
2. Set the `.query.pq` test file's contents to something simple, like `123`.
3. Evaluate the test file, requesting logs to be output (arg `-l`).
    ````
    PQTest.exe run-test `
    >> --extension SomeExtension.mez `
    >> --queryFile SomeExtension.query.pq `
    >> --prettyPrint `
    >> -l all
    ````

### Actual Experience

Each log line output is in the form of:
(for clarity, tab characters have been replaced with`\t`)
````
\t2023-01-10T14:52:18.6442718Z\tRemoteServiceEnvironment/CreateServiceStubs\tHostProcessId: 9128, CorrelationId: \t00:00:00.0765380\t9128\t7
````

Notice that `CorrelationId`'s value is a blank space.

### Expected Experience

The actual correlation ID should be output (the value of `Diagnostics.ActivityId`?).

**Comment by mattmasson** [comment]
`CorrelationId` and `ActivityId` are two different fields/values. Currently, the `ActivityId` value is used in the name of the log file. `CorrelationId` is an arbitrary string value that can be set by the mashup engine's host process, but we currently don't have a use case for it through the SDK.

**Comment by bgribaudo** [comment]
Thanks, @mattmasson!
