### ISSUE TITLE
Create New Project Command Not Found

### ISSUE THREAD

**Issue by ScarlettCode** [microsoft/vscode-powerquery-sdk#218]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.1

### Platform

Windows

### Architecture

x64

### OS Version

Windows 11 with Parallels on M1 Mac

### VSCode version

1.74.3

### Bug Description

When running "Power query: Create an extension project" (Or any other Power Query option from the command palette) I get the following error

Command 'Power query: Create an extension project' resulted in an error (command 'powerquery.sdk.tools.CreateNewProjectCommand' not found)

### Steps to Reproduce

1. Install extension
2. Open command palette and run Power query: Create an extension project
3. Error

### Actual Experience

![Screenshot 2023-01-19 at 12 20 08](https://user-images.githubusercontent.com/786389/213416993-cd3acd43-3ede-4e2f-811e-9e48c1c6adde.png)

### Additional Context

I'm running VS Code on Windows 11 through Parallels Desktop on a Mac. Is the ARM version of windows missing something that's causing this?

**Comment by kerski** [comment]
I have the same issue on a Windows 11 machine with ARM.  I uninstalled VS Code and removed my .vscode and app data.  Then I reinstalled VS Code, add the SDK through extensions, and got the same error.
