### ISSUE TITLE
Native Query UI - Case-Insensitive Navigation Step Search

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#220]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Problem

Currently, values the user inputs in the native query UI which are mapped to `navigationSteps` are used to search the navigation table in a **case-sensitive** manner.

However, server/host names are **case-insensitive**. Also, some external systems have object names (database names, table names, etc.) which are case-insensitive. In cases like these, performing this search in a case-sensitive matter hinders usability, as the user won't necessarily know the correct casing to use.

For example, if a user wants to run a native query against "ServerA" using the below dialog, should they enter the server name as "ServerA", "servera", "SERVERA" or something else. As DNS hostnames are case-insensitive, any of these are valid at the hostname level, but only one will be accepted by the native query dialog. 

![image](https://user-images.githubusercontent.com/857202/214636015-fc842e7b-eb9d-4e77-bd40-edc2238b45ca.png)

### Desired Solution

A way to instruct the native query UI to search the navigation table for the user-inputted value in a **case-insensitive** way.

Idea: 
Add a `caseInsenstive` option to the nav step's configuration.
````
navigationSteps = {[indices = {
  [
    value = "server",
    indexName = "Name",
    caseInsensitive = true
  ]
} ... ]
````
When set to true:
* The native query UI would search the nav table for the specified value in a case-insensitive manner. 
* If a match is found, its name would be read verbatim out of the nav table and written into the row-selection code generated by the UI. 

Example: 
* User enters "servera". 
* Native Query UI looks in the nav table for "servera" (case-insensitive) and finds that "ServerA" matches. 
* It then uses the found value ("ServerA") to generate the following M code (which is case-sensitive):
    ````
    Value.NativeQuery(NativeTest.Contents("ServerA"){[Name="ServerA"]}[Data], "123", null, null)
    ````

**Comment by mattmasson** [comment]
I think this would require some fundamental changes to the way the PQ UI code (or the M engine) works.

The PQ UI uses the native query settings hints to generate a formula. There's no evaluation step to list the databases or mechanism for rewriting the user's input. 

For what it's worth, the case insensitive lookup ("servera") can actually work today if (a) the connector has implemented navigation table folding, and (b) the backend data source supports case insensitive lookups. (Nav table folding isn't widely implemented or documented (it's tricky to get right), but it essentially allows the connector to assume the nav path is valid and skip listing the non-leaf levels of the nav table)

There are a couple of proposed UX improvements that would make this less of an issue:

1. From the navigator view, allow the user to "run native query at this level"
2. Allow authenticated calls to be made on the data source settings dialog, which would allow the connector to populate a "Database" drop down list

As always, thank you for the suggestions! We are making a number of updates to the Native Query support specification (currently targeted for April) that are a direct result of your input.

**Comment by bgribaudo** [comment]
Thank you, @mattmasson!
