### ISSUE TITLE
Python.Execute is an unknown identifier within the SDK

### ISSUE THREAD

**Issue by erenmirza** [microsoft/vscode-powerquery-sdk#241]
Within the any .pq file, the command `Python.Execute` is not supported within the Power Query SDK.

Would it be possible to add support in for this to allow the development of Custom Connectors leveraging Python?

![image](https://user-images.githubusercontent.com/79056069/221212964-7b620f13-ccab-4bdd-b3b6-9fdffbd0a331.png)

**Comment by mattmasson** [comment]
There are no plans to support calling other extensions from a custom connector at this time (particularly ones that require external runtimes, like R and Python).
