### ISSUE TITLE
What .NET SDK to target? Samples have lots of build errors.

### ISSUE THREAD

**Issue by CraigChamberlain** [microsoft/vscode-powerquery-sdk#242]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

-

### Platform

All

### Architecture

i86

### VSCode version

-

### PQSdkTool Path

-

### Bug Description

I have been getting various build errors when building the [github sample](https://github.com/microsoft/DataConnectors/tree/master/samples/Github)  would have post an issue over there but doesn't have a board.

I have the following SDKs installed:
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
7.0.103 [C:\Program Files\dotnet\sdk]
7.0.200 [C:\Program Files\dotnet\sdk]

And my build is defaulting to MSBuild version 17.4.1

I thought I'd have a go updating line 83 of github.mproj original:
<UsingTask TaskName="BuildExtension" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v12.0.dll">

to:
<UsingTask TaskName="BuildExtension" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v12.0.dll">

but this spawned more errors.  I think that it would be great to have either a .NET 7 branch or an instruction in the examples or this page describing the maximum MSBuild version/ .NET SDK as I understand the Repo is going to have to also support VS 2019 for some time too.

### Steps to Reproduce

1. Install .NET 7 SDK
2. Checkout https://github.com/microsoft/DataConnectors/
3. Attempt to build /master/samples/Github `dotnet build`

### Actual Experience

You should get some build errors.
```

C:\Users\Craig\source\repos\DataConnectors\samples\Github\github.mproj(120,5): error MSB4801: The task fact 
ory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.

```
```
C:\Users\Craig\source\repos\DataConnectors\samples\Github\github.mproj(119,5): error MSB4175: The task fact
ory "RoslynCodeTaskFactory" could not be loaded from the assembly "C:\Program Files\dotnet\sdk\7.0.103\Micr 
osoft.Build.Tasks.v12.0.dll". Could not load file or assembly 'C:\Program Files\dotnet\sdk\7.0.103\Microsof 
t.Build.Tasks.v12.0.dll'. The system cannot find the file specified.
```

**Comment by CraigChamberlain** [comment]
I installed windows development kit 10.0.19041 to get access to a framework version of the .NET SDK and had some satisfaction building in Visual Studio 19 using the terminal command `msbuild` not `dontnet build`.  This is only available from Developer PowerShell and so doesn't work in VS code with the standard PowerShell Terminal.

I think it should be easier to make the samples work.  I know this isn't a bug with this SDK but I can't make an issue on the relevant repo: https://github.com/microsoft/DataConnectors

**Comment by mattmasson** [comment]
The current DataConnectors samples are still targeting the PQ SDK for Visual Studio extension, which works with VS 2019. We were planning on migrating the project files from the 2019 .mproj format to the new .proj format we're using in VS Code once we reach General Availability with our VS Code extension.

Tagging @ptyx507x as a reminder. 

Note that .mez files are just zips, so you can run the "build" in a variety of ways.

Until the project files have been migrated, you can open the directory in VS Code and use the "Create an extension project" option to generate vscode compatible project files.
