### ISSUE TITLE
Text values are being ignored from the dataSourcePath

### ISSUE THREAD

**Issue by waldyd** [microsoft/vscode-powerquery-sdk#276]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.3

### Platform

Windows

### Architecture

x64

### OS Version

Windows 10

### VSCode version

1.78.2

### PQSdkTool Path

C:\$HOME\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.3-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\

### Bug Description

Text values are being ignored from the dataSourcePath:

![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/1531796/58226558-c9eb-4582-a5d1-494350658cb2)

### Steps to Reproduce

1. Open the test file for the data connector (*.query.pq)
2. Define a dataSourcePath with text values:
`dataSourcePath =  Json.FromValue([Division = "66207", Country = "US"])`
3. Evaluate the file

### Actual Experience

1. The credentials are not correctly saved:
![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/1531796/e8d91032-8f6e-4d7d-b9a2-8246f68617da)
2. The test connection function is also ignoring the values:
![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/1531796/a17772ed-1f7c-417c-9680-5335f5d2d3d1)

### Expected Experience

dataSourcePath text values not being ignored.

### Additional Context

![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/1531796/bf167727-e3ed-4603-a18a-46aaf239cfed)

```json
[
    {
        "ActivityId": "0544bcab-0311-4c76-8a81-2075d6812492",
        "DataSourceAnalysis": [
            {
                "Kind": "DataSource",
                "FunctionName": "ExactAPIConnector.Contents",
                "DataSource": {
                    "Kind": "ExactAPIConnector",
                    "NormalizedPath": "{\"Division\":\"\",\"Country\":\"\"}",
                    "Path": "{\"Division\":\"\",\"Country\":\"\"}"
                }
            }
        ],
        "Details": "Credentials are required to connect to the ExactAPIConnector source. (Source at {\"Division\":66207,\"Country\":\"US\"}.)",
        "EndTime": "2023-05-26T12:01:53.1331263+00:00",
        "Method": "PQTest.RunTest",
        "Name": "ExactAPIConnector.query.pq",
        "StartTime": "2023-05-26T12:01:48.5092018+00:00",
        "RowCount": 0,
        "Status": "Failed",
        "Type": "PQTest.Expression",
        "Error": {
            "Message": "Credentials are required to connect to the ExactAPIConnector source. (Source at {\"Division\":66207,\"Country\":\"US\"}.)",
            "Details": {
                "Microsoft.Data.Mashup.CredentialError.Reason": "CredentialMissing",
                "Microsoft.Data.Mashup.CredentialError.DataSourceKind": "ExactAPIConnector",
                "Microsoft.Data.Mashup.CredentialError.DataSourcePath": "{\"Division\":66207,\"Country\":\"US\"}",
                "Microsoft.Data.Mashup.MashupSecurityException.Reason": "CredentialMissing",
                "Microsoft.Data.Mashup.MashupSecurityException.DataSources": "[{\"kind\":\"ExactAPIConnector\",\"path\":\"{\\\"Division\\\":66207,\\\"Country\\\":\\\"US\\\"}\"}]"
            }
        }
    }
]
```

**Comment by mattmasson** [comment]
Does the test file work as expected if you use literals for the function parameters (`ExactAPIConnector.Contents(66207, "US")`) rather than extracting them using `Json.FromValue`?

This is likely a limitation with the _static analysis_ we run over the test file to determine the credentials needed to run the query. It is similar to what's done when configuring scheduled refresh in the Power BI service. The analysis supports simple variable substitutions and literal values but wouldn't know what `Json.FromValue` returns or infer the values for the `division` and `country` variables.

That said, I see a couple of improvements we can make:

1. Support dynamic credential lookup.
2. Fix the `DataSourceAnalysis` entry in the results to make it clear that static analysis was unable to figure out the correct Path value.

**Comment by mattmasson** [comment]
There is still some room for improvement, but the behavior is better in the [0.3.1 release](https://github.com/microsoft/vscode-powerquery-sdk/releases/tag/v0.3.1) (sdktools `2.127.2`).

The `set-credential` command is still limited to doing static analysis, but `run-test` now supports dynamic credential lookup at runtime. That means you have to manually create a credential by running the `set-credential` command, but once the credential is available, it will be found at runtime even if you're doing some form of dynamic data source access.
