### ISSUE TITLE
Could not load file or assembly Microsoft.Extensions.CommandLineUtils

### ISSUE THREAD

**Issue by CraigRaelHarris** [microsoft/vscode-powerquery-sdk#277]
I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
 I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
 I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

Power Query SDK
0.2.3

Regression From
No response

Platform
Windows

Architecture
x64

OS Version
Windows 10

VSCode version
1.78.2

PQSdkTool Path
C:$HOME.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.3-win32-x64.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools\

Bug Description

PQTest.Console.Program.Main
Various processes throw the error that it cannot find the dll. Clean install of laptop, Visual Code and dotnet SDKs

Full error
[Error]	[Task exited abnormally] pqtest info pid(20668) exit(3762504530) stderr: 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at PQTest.Console.Program.Main(String[] args)

Installed sdks and runtimes
6.0.408 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.302 [C:\Program Files\dotnet\sdk]
Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

   
Steps to Reproduce
Install extension and create a new project. 
![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/5291055/17243a36-9c13-4507-9278-8724beef5cf9)

**Comment by CraigRaelHarris** [comment]
This works in 0.2.2
Missing DLLs in the 
\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.2-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools
folder in 0.2.3

**Comment by CraigRaelHarris** [comment]
This works in 0.2.2
Missing DLLs in the
.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.2-win32-x64.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\tools
folder in 0.2.3

**Comment by StephenOTT** [comment]
Was this fixed?  Still seeing this issue in 0.2.3.  We had to downgrade to 0.2.2, run the ask install, then re-upgrade to 0.2.3.
