### ISSUE TITLE
Support for PowerPlatform and CommonDataService namespaces

### ISSUE THREAD

**Issue by kerski** [microsoft/vscode-powerquery-sdk#285]
### Preflight Checklist

- [X] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [X] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [X] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.2.3

### Platform

Windows

### Architecture

x64

### OS Version

Windows 11

### VSCode version

1.80.2

### PQSdkTool Path

.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.3-win32-arm64\.nuget\Microsoft.PowerQuery.SdkTools.2.114.4\

### Bug Description

I'm curious why the CommonDataService and PowerPlatform and PowerBI connectors namespaces are not available when building a connector in the SDK.  For example if I write CommonDataService.Database in a .pq file in the SDK, this name cannot be found.

However other namespaces for Microsoft products (e.g., AzureStorage) are available.

Thank you.

### Steps to Reproduce

For example if I write CommonDataService.Database in a .pq file in the SDK, this name cannot be found.

### Actual Experience

For example if I write CommonDataService.Database in a .pq file in the SDK, this name cannot be found.

### Expected Experience

N/A

### Additional Context

N/A

**Comment by mattmasson** [comment]
Tracked in the vscode-powerquery repo.
https://github.com/microsoft/vscode-powerquery/issues/206
