### ISSUE TITLE
Compatibility with VSCode.dev

### ISSUE THREAD

**Issue by sancarn** [microsoft/vscode-powerquery-sdk#300]
### Problem

Cannot use Power Query SDK on VSCode.dev (vscode online).

### Desired Solution

Ability to use builder online - this would be especially useful for businesses who don't have the permissions to install software on their systems.

### Additional Context

From looking at the `.mez` files there doesn't appear to be any need to have binaries, so don't see why this wouldn't be compatible with the web (they are just zip files containing an `xml` file, images and `pq` files.

**Comment by mattmasson** [comment]
Hello - this extension relies on a set of external tools to actually run and test connector code. We wouldn't be able to support this in a web environment.

I opened a tracking item to add vscode.dev support to the vscode-powerquery language service extension.
https://github.com/microsoft/vscode-powerquery/issues/207

**Comment by sancarn** [comment]
> relies on a set of external tools to actually run

Assume you're talking about the powerquery-sdk?  Couldn't the pq-sdk be compiled to wasm such that it can run in the browser?

**Comment by mattmasson** [comment]
> Assume you're talking about the powerquery-sdk? Couldn't the pq-sdk be compiled to wasm such that it can run in the browser?

The evaluation of the M query requires our runtime engine (M/Mashup Engine). The `vscode-powerquery-sdk` extension downloads the [Microsoft.PowerQuery.SdkTools nuget package](https://www.nuget.org/packages/Microsoft.PowerQuery.SdkTools) in the background and uses the `pqtest.exe` utility to perform the actual evaluations.

Making the entire engine run under WASM is interesting, but unlikely to happen.
