### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by SamGirv** [microsoft/vscode-powerquery-sdk#327]
When I try to install Power Query SDK onto Microsoft Visual I get the following error:
 ![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/99924327/4b6922e5-6c37-4959-8e29-c2d4d71c38f5)
"The document's format is either unsupported or the document contains binary characters, opening with a different application." and when I press "OK" I get:
![image](https://github.com/microsoft/vscode-powerquery-sdk/assets/99924327/46fd1d1c-34bc-4cdd-928e-0b7324788529)

Any suggestions on how to install the extension?

Thanks in advance.

**Comment by mattmasson** [comment]
Note this extension is for Visual Studio Code.

You can install the extension from the VS Code IDE.
For an offline install, download the .vsix file and install from the command line

```
code --install-extension path_to_file.vsix
```

See: https://code.visualstudio.com/learn/get-started/extensions
