### ISSUE TITLE
No error highlighting when attempting to use Folder.Files or File.Contents

### ISSUE THREAD

**Issue by mark-codylor** [microsoft/vscode-powerquery-sdk#342]
### Preflight Checklist

- [x] I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
- [x] I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
- [x] I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).

### Power Query SDK

0.4.0

### Platform

Windows

### Architecture

x64

### OS Version

Windows 11

### VSCode version

1.94.1

### Bug Description

It appears that using Folder.Files or File.Contents in custom connectors is forbidden (although I can't find anything official noted anywhere).

The linting doesn't flag these as unusable and doesn't put red lines under them.

Side note if:  If there is a way to use these, then it isn't documented and doesn't work when attempting to test in vscode.

### Steps to Reproduce

1. Launch VSC
2. Use Power Query SDK to generate Hello world example
3. Adapt the Contents function to invoke Folder.Files()

### Actual Experience

Actual Result

When running the .query.pq

- "Credentials are required to connect to the MyCustomConnector source."

- No syntax highlighting to warn of any issues

### Expected Experience

- It works
or
- The function is flagged as unrecognised

**Comment by mattmasson** [comment]
Custom Connectors can't access the file system (for security reasons).

The list of data source functions that can be wrapped with a custom connector can be found here: https://learn.microsoft.com/en-us/power-query/handling-data-access#data-source-functions
