### ISSUE TITLE
Ensure extension path value in settings.json file is correct when creating a new project

### ISSUE THREAD

**Issue by mattmasson** [microsoft/vscode-powerquery-sdk#59]
The default msbuild template sets the output path to `bin\connector,mez`, but the default settings.json file sets it to `bin\AnyCPU\Debug\connector.mez`.

We should decide on what we want to use for the default location for the SDK build and our initial msbuild file.

Existing .mproj files would likely be defaulting their output to `bin\AnyCPU\Debug` by default.

**Comment by dwolfeu** [comment]
I think I may have found a bug related to this issue. My `settings.json` file is as follows:

```json
{
  "powerquery.sdk.defaultQueryFile": "${workspaceFolder}\\${workspaceFolderBasename}.query.pq",
  "powerquery.sdk.defaultExtension": "${workspaceFolder}\\bin\\Debug\\${workspaceFolderBasename}.mez",
  "powerquery.general.mode": "SDK"
}
```

However, when I build the project the `.mez` file is saved with the file path `${workspaceFolder}\\bin\\AnyCPU\\Debug\\${workspaceFolderBasename}.mez`. While the build task is running, this file path (as an absolute path, i.e. with no variables) appears in the terminal as the value of `TargetMezRootPath`.

Is this a bug or am I doing something wrong? It's not a big deal, it's just that I'm working on an extension project that someone else authored and I would like to preserve the directory structure.

**Comment by dwolfeu** [comment]
I'm looking forward to trying this out with the next release. Do the changes mean that the output path for the `.mez` will be completely customisable? That is, if `settings.json` looks this this...

```json
{
  "powerquery.sdk.defaultQueryFile": "${workspaceFolder}\\${workspaceFolderBasename}.query.pq",
  "powerquery.sdk.defaultExtension": "...\\foo\\bar\\baz.mez",
  "powerquery.general.mode": "SDK"
}
```

... then will the `.mez` file indeed be saved as `...\\foo\\bar\\baz.mez`?
