### ISSUE TITLE
[Design] SDK vs. MSBuild

### ISSUE THREAD

**Issue by mattmasson** [microsoft/vscode-powerquery-sdk#60]
Our default connector template comes with an msbuild file (connector.proj), but defaults to using the SDK build mechanism. This might be confusing for users.

We should remove the .proj from our template if we are defaulting to the SDK build.

That said, generating a new proj file from scratch can be difficult, and it would be great to replace the existing .mproj file (which targets an older msbuild) with a newer/simplified .proj file that uses modern msbuild features.

**Design questions**

1. Should we make the SDK build vs. MSBuild a choice when you create a connector?
2. Can we add an "enable for MSBuild" command that changes the default build mode to msbuild and generates a new proj file based on the current workspace contents? 

I don't feel strongly about (1), but I would lean towards not making a new connector option, since the use of msbuild is likely a more advanced scenario. I do see value in (2) though, especially as we continue to improve the default build template (making it easier to sign extensions, insert localization steps, etc)... but you could argue that a developer could simply copy their msbuild definition from published templates or samples.

**Comment by bgribaudo** [comment]
Are you strongly married to keeping both build system options? For simplicity, would there be any chance to standardize on just one (i.e. MSBuild, if that is needed because if its support for advanced scenarios)?

Thinking that a beginner user may not need to touch the build file, so whether SDK or MSBuild is used doesn't affect them. For an advanced user, likely the additional SDK-related options they need to set wouldn't be too complex to set in either style build file, so maybe just supporting one style would be sufficient??

**Comment by bgribaudo** [comment]
Related: How many of the legacy SDK's options do you anticipate the new SDK will support (perhaps with different syntax/command line args)?

````
  <AllowNativeQuery>True</AllowNativeQuery>
  <AsAction>True</AsAction>
  <FastCombine>True</FastCombine> -- irrelevant, as in the new SDK this behavior is enabled by default and cannot be turned off
  <ClearLog>True</ClearLog> -- irrelevant, as new SDK traces are output to files
  <ShowEngineTraces>True</ShowEngineTraces> -- handled by --logMashupEngineTraces
  <ShowUserTraces>True</ShowUserTraces> -- handled by --logMashupEngineTraces
  <LegacyRedirects>True</LegacyRedirects>
  <SuppressRowErrors>True</SuppressRowErrors>
  <SuppressCellErrors>True</SuppressCellErrors>
  <MaxRows>1000</MaxRows>
  <ThrowOnFoldingFailure>True</ThrowOnFoldingFailure> -- handled by --failOnFoldingFailure
````
