### ISSUE TITLE
Feature Suggestion - Offer a Firewall-Enabled Mode

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#98]
My understanding is that the new SDK operates without Power Query's data protection firewall running.

From Power Query's perspective, everything inside a connector (well, technically, inside a data source kind, I believe) is considered a single data source for data protection partitioning purposes. So, within a data source kind, the fact that the firewall isn't present with the SDK is a moot point.

However, the SDK allows M code outside of the connector/outside of a data source kind to run, specifically the code in the MyConnector.query.pq test file. The code in this test file can pull from multiple data source kinds that are defined in the project's connector, as well as from other connectors that ship with Power Query. 

In order for behavior to match between the SDK and other Power Query environments (e.g. PQ in Power BI or Excel), it would be nice to have the option in the SDK to have the firewall enabled and operating normally so that code inside the .query.pq test file is properly partitioned and firewalled.

Thank you for your consideration!

**Comment by mattmasson** [comment]
Exposing privacy levels makes sense if we expand the scope of the SDK to cover general PQ scenarios, but at this time it is focused on connector development.

The SDK lets you run test queries for logic you'll be putting into your data source, and data source calls made from inside a connector are done within a single firewall partition. To replicate this behavior, all SDK evaluations are done with Fast Combine / "Ignore Privacy Levels" enabled.
